language: clojure
lein: 2.7.1
jdk:
  - openjdk8
script: ./ext/travisci/test.sh
notifications:
  email: false

# workaround for buffer overflow issue, ref https://github.com/travis-ci/travis-ci/issues/5227
addons:
  hosts:
    - myshorthost
  hostname: myshorthost
